[package]
name = "veilzero_protocol"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.18.0"

[dev-dependencies]
cairo_test = "2.18.0"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "scarb cairo-test"
